set-window-option -g mode-keys vi
unbind -Tcopy-mode-vi Enter
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

set -s escape-time 20
